/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as StudentResourcesRouteImport } from './routes/student-resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnlineLearningRouteImport } from './routes/online-learning'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerGuidanceRouteImport } from './routes/career-guidance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/student-resources',
  path: '/student-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineLearningRoute = OnlineLearningRouteImport.update({
  id: '/online-learning',
  path: '/online-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuidanceRoute = CareerGuidanceRouteImport.update({
  id: '/career-guidance',
  path: '/career-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/online-learning': typeof OnlineLearningRoute
  '/privacy': typeof PrivacyRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-resources': typeof StudentResourcesRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/online-learning': typeof OnlineLearningRoute
  '/privacy': typeof PrivacyRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-resources': typeof StudentResourcesRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/online-learning': typeof OnlineLearningRoute
  '/privacy': typeof PrivacyRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-resources': typeof StudentResourcesRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career-guidance'
    | '/contact'
    | '/courses'
    | '/disclaimer'
    | '/faq'
    | '/online-learning'
    | '/privacy'
    | '/scholarships'
    | '/services'
    | '/sitemap.xml'
    | '/student-resources'
    | '/study-abroad'
    | '/universities'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career-guidance'
    | '/contact'
    | '/courses'
    | '/disclaimer'
    | '/faq'
    | '/online-learning'
    | '/privacy'
    | '/scholarships'
    | '/services'
    | '/sitemap.xml'
    | '/student-resources'
    | '/study-abroad'
    | '/universities'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career-guidance'
    | '/contact'
    | '/courses'
    | '/disclaimer'
    | '/faq'
    | '/online-learning'
    | '/privacy'
    | '/scholarships'
    | '/services'
    | '/sitemap.xml'
    | '/student-resources'
    | '/study-abroad'
    | '/universities'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerGuidanceRoute: typeof CareerGuidanceRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  OnlineLearningRoute: typeof OnlineLearningRoute
  PrivacyRoute: typeof PrivacyRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudyAbroadRoute: typeof StudyAbroadRoute
  UniversitiesRoute: typeof UniversitiesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-resources': {
      id: '/student-resources'
      path: '/student-resources'
      fullPath: '/student-resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-learning': {
      id: '/online-learning'
      path: '/online-learning'
      fullPath: '/online-learning'
      preLoaderRoute: typeof OnlineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guidance': {
      id: '/career-guidance'
      path: '/career-guidance'
      fullPath: '/career-guidance'
      preLoaderRoute: typeof CareerGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerGuidanceRoute: CareerGuidanceRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  OnlineLearningRoute: OnlineLearningRoute,
  PrivacyRoute: PrivacyRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentResourcesRoute: StudentResourcesRoute,
  StudyAbroadRoute: StudyAbroadRoute,
  UniversitiesRoute: UniversitiesRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
